apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
  namespace: infra
data:
  ASPNETCORE_ENVIRONMENT: Development

  HTTP_ADMIN_PORT: "8013"

  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgresservice
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak

  KEYCLOAK_PORT: "8080"
  KEYCLOAK_URL: "http://keycloakservice:8080"
  KEYCLOAK_ADMIN_USER: admin
  KEYCLOAK_CLIENT_ID: admin-cli
  