apiVersion: v1
kind: Service
metadata:
  name: mtadminservice
  namespace: infra
spec:
  type: NodePort
  selector:
    app: mtadmin
  ports:
    - port: 8013        # порт внутри кластера
      targetPort: 8013  # порт контейнера
      nodePort: 30013   # доступ с хоста через localhost:30013
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtadmin
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtadmin
  template:
    metadata:
      labels:
        app: mtadmin
    spec:
      containers:
        - name: mtadmin
          image: pruginkad/mtadminserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8013
          envFrom:
            - configMapRef:
                name: infra-config    # все обычные переменные
            - secretRef:
                name: infra-secret    # все пароли
