apiVersion: apps/v1
kind: Deployment
metadata:
  name: placement
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placement
  template:
    metadata:
      labels:
        app: placement
    spec:
      containers:
        - name: placement
          image: daprio/placement:latest
          args:
            - ./placement
            - "-port"
            - "50006"
          ports:
            - containerPort: 50006
