# ===============================
# ConfigMap для общих переменных
# ===============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
  namespace: infra
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_HOST: postgresservice
  POSTGRES_PORT: "5432"

---
# ===============================
# Secret для паролей
# ===============================
apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
  namespace: infra
type: Opaque
stringData:
  POSTGRES_PASSWORD: password

---
# ===============================
# Service для Postgres
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: postgresservice
  namespace: infra
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30042

---
# ===============================
# PersistentVolume
# ===============================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: infra
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Важно: путь к папке на диске Windows через /host_mnt/d/…
    path: /host_mnt/d/TESTS/multitenant_admin/mt_admin/root_data/postgres_data

---
# ===============================
# PersistentVolumeClaim
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# ===============================
# Deployment Postgres
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: infra-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: infra-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
