apiVersion: apps/v1
kind: Deployment
metadata:
  name: aasubservice
  namespace: myrealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aasubservice
  template:
    metadata:
      labels:
        app: aasubservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "aasubservice"
        dapr.io/app-port: "20008"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: app
          image: pruginkad/aasubservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 20008
          envFrom:
            - configMapRef:
                name: myrealm-env
          env:
            - name: APP_PORT
              value: "20008"
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: myrealm-env
                  key: AASUBSERVICE_APP_ID
---
apiVersion: v1
kind: Service
metadata:
  name: aasubservice
  namespace: myrealm
spec:
  type: NodePort
  clusterIP: ""
  selector:
    app: aasubservice
  ports:
    - port: 20008
