apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinkservice
  namespace: myrealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blinkservice
  template:
    metadata:
      labels:
        app: blinkservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "blinkservice"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: app
          image: pruginkad/blinkservice:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: myrealm-env
          env:
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: myrealm-env
                  key: BLINK_APP_ID
