apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpctracksclient
  namespace: myrealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpctracksclient
  template:
    metadata:
      labels:
        app: grpctracksclient
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "grpctracksclient"
        dapr.io/app-port: "20007"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: app
          image: pruginkad/grpctracksclient:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 20007
          envFrom:
            - configMapRef:
                name: myrealm-env
          env:
            - name: APP_PORT
              value: "20007"
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: myrealm-env
                  key: TRACKS_CLIENT_APP_ID
