apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafletalarms
  namespace: myrealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leafletalarms
  template:
    metadata:
      labels:
        app: leafletalarms
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "leafletalarms"
        dapr.io/app-port: "5000"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: app
          image: pruginkad/leafletalarms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: myrealm-env
            - secretRef:
                name: myrealm-secrets
          env:
            - name: GRPC_MAIN_PORT
              value: "5000"
            - name: HTTP_PORT
              value: "8000"
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: myrealm-env
                  key: LEAFLETALARM_APP_ID

          volumeMounts:
            - name: leaflet-data
              mountPath: /leaflet_data
      volumes:
        - name: leaflet-data
          hostPath:
            path: /data/leaflet
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: leafletalarms
  namespace: myrealm
spec:
  type: NodePort
  selector:
    app: leafletalarms
  ports:
    - name: grpc
      port: 5000
      targetPort: 5000
    - name: http
      port: 8000
      targetPort: 8000
      #nodePort: 30001
