apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
  namespace: myrealm   # или default / infra
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis.infra.svc.cluster.local:6379
    - name: redisPassword
      value: ""
